// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAuthValidationException extends ApiException {
    public static final Integer ERROR_CODE = 17;

    public static final String ERROR_DESCRIPTION = "Validation required";

    private String redirectUri;

    public ApiAuthValidationException(Error error, String redirectUri) {
        super(error.setErrorText(ERROR_DESCRIPTION));
        this.redirectUri = redirectUri;
    }

    public ApiAuthValidationException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }

    public String getRedirectUri() {
        return redirectUri;
    }
}
