// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiCaptchaException extends ApiException {
    public static final Integer ERROR_CODE = 14;

    public static final String ERROR_DESCRIPTION = "Captcha needed";

    private String sid;

    private String image;

    public ApiCaptchaException(Error error, String sid, String image) {
        super(error.setErrorText(ERROR_DESCRIPTION));
        this.sid = sid;
        this.image = image;
    }

    public ApiCaptchaException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }

    public String getSid() {
        return sid;
    }

    public String getImage() {
        return image;
    }
}
